import { atom, read, update } from 'claude-code'
import type { EngineInterface, Register } from 'claude-code'

import type { Artifact } from '../types'
import { formatSize, formatTime, parseStatus } from './lib'

const PANE = 'enhance-artifacts'
const REFRESH_MS = 15 * 60 * 1000
const ARTIFACT_LIMIT = 100

const artifacts = atom({ plugin: 'enhance-companion', key: 'artifacts' } as const, [] as Artifact[])
const status = atom({ plugin: 'enhance-companion', key: 'status' } as const, null)

/** Locates the installed cc-enhance entrypoint, whatever marketplace name it came from. */
async function enhanceDist($: EngineInterface): Promise<string | undefined> {
  const home = await $.env.get('HOME')
  if (!home) return undefined
  try {
    const data = JSON.parse(await $.fs.read(`${home}/.claude/plugins/installed_plugins.json`)) as {
      plugins?: Record<string, { installPath?: string }[]>
    }
    const plugins = data.plugins ?? {}
    for (const key of Object.keys(plugins)) {
      if (!key.startsWith('cc-enhance@')) continue
      const install = plugins[key]?.[0]?.installPath
      if (!install) continue
      const dist = `${install}/dist/cc-enhance.mjs`
      if (await $.fs.exists(dist)) return dist
    }
  } catch {
    // Fall through to the marketplace checkout.
  }
  const checkout = `${home}/.claude/plugins/marketplaces/agent-enhance/dist/cc-enhance.mjs`
  return (await $.fs.exists(checkout)) ? checkout : undefined
}

async function refreshStatus($: EngineInterface): Promise<void> {
  const dist = await enhanceDist($)
  if (dist === undefined) {
    await update($, status, () => ({ error: 'cc-enhance not installed' }))
    return
  }
  try {
    const run = await $.process.run(['node', dist, 'cli', 'status'], { timeoutMs: 60_000 })
    if (run.exitCode !== 0) {
      await update($, status, () => ({ error: 'status failed' }))
      return
    }
    const { caps, connections } = parseStatus(run.stdout)
    await update($, status, () => ({ caps, connections }))
  } catch {
    await update($, status, () => ({ error: 'status unavailable' }))
  }
}

/**
 * Scans ~/.agent-enhance/artifacts/claude-code/<tool>/<provider>/<session>/<call>/<file>,
 * newest first. There is no index file; the directory tree is the record.
 */
async function scanArtifacts($: EngineInterface): Promise<Artifact[]> {
  const home = await $.env.get('HOME')
  if (!home) return []
  const root = `${home}/.agent-enhance/artifacts/claude-code`
  if (!(await $.fs.exists(root))) return []
  const found: Artifact[] = []
  const dirs = (path: string) => $.fs.list(path).catch(() => [])
  for (const tool of await dirs(root)) {
    if (tool.kind !== 'dir') continue
    for (const provider of await dirs(`${root}/${tool.name}`)) {
      if (provider.kind !== 'dir') continue
      for (const session of await dirs(`${root}/${tool.name}/${provider.name}`)) {
        if (session.kind !== 'dir') continue
        const callRoot = `${root}/${tool.name}/${provider.name}/${session.name}`
        for (const call of await dirs(callRoot)) {
          if (call.kind !== 'dir') continue
          for (const file of await dirs(`${callRoot}/${call.name}`)) {
            if (file.kind !== 'file') continue
            found.push({
              path: `${callRoot}/${call.name}/${file.name}`,
              tool: tool.name,
              provider: provider.name,
              file: file.name,
              mtimeMs: file.mtimeMs,
              size: file.size,
            })
          }
        }
      }
    }
  }
  return found.sort((a, b) => b.mtimeMs - a.mtimeMs).slice(0, ARTIFACT_LIMIT)
}

export const register: Register = on => {
  on('session.start', async ($, e, next) => {
    await $.command.register({
      name: 'enhance-artifacts',
      description: 'Browse files generated by cc-enhance in a pane',
    })
    await refreshStatus($)
    $.clock.every(REFRESH_MS, () => refreshStatus($))
    return next(e)
  })

  on('command.run', { command: 'enhance-artifacts' }, async $ => {
    const found = await scanArtifacts($)
    await update($, artifacts, () => found)
    const opened = await $.ui.open({ id: PANE, title: 'Enhance artifacts' })
    if (!opened.isPlaced) {
      return { text: `Artifact pane could not open: ${opened.reason}` }
    }
    return {
      text:
        found.length === 0
          ? 'No cc-enhance artifacts yet.'
          : `${found.length} artifacts, newest first.`,
    }
  })

  on('ui.render', { component: 'AbovePrompt' }, async ($, e, next) => {
    const s = await read($, status)
    if (s === null) return next(e)

    const { Box, Text } = $.ui.resolve(e)
    if ('error' in s) {
      return (
        <Box>
          <Text dimColor>⚡ enhance </Text>
          <Text color="yellow">{s.error}</Text>
        </Box>
      )
    }
    if (s.caps.length === 0) {
      return (
        <Box>
          <Text dimColor>⚡ enhance </Text>
          <Text color="yellow">nothing available</Text>
        </Box>
      )
    }
    return (
      <Box>
        <Text dimColor>⚡ enhance </Text>
        <Text color="green">{s.caps.join('·')}</Text>
        <Text dimColor> · {s.connections} conn</Text>
      </Box>
    )
  })

  on('ui.render', { component: 'Pane', requestId: PANE }, async ($, e) => {
    const { Box, Button, Text } = $.ui.resolve(e)
    const list = await read($, artifacts)
    const room = Math.max(1, (e.viewport?.rows ?? 24) - 5)

    return (
      <Box flexDirection="column">
        <Box>
          <Button
            key="refresh"
            label="Refresh"
            onPress={async () => {
              const found = await scanArtifacts($)
              await update($, artifacts, () => found)
            }}
          />
        </Box>
        {list.length === 0 && (
          <Text dimColor>No artifacts under ~/.agent-enhance/artifacts yet.</Text>
        )}
        {list.slice(0, room).map((a, i) => (
          <Box key={a.path}>
            <Text dimColor>{formatTime(a.mtimeMs)}  </Text>
            <Text>
              {a.tool}/{a.provider} {a.file} ({formatSize(a.size)}){' '}
            </Text>
            <Button
              key={`copy:${i}`}
              plain
              label="copy"
              onPress={async () => {
                const copied = await $.ui.copy({ text: a.path })
                $.ui.toast(copied.isCopied ? `copied: ${a.file}` : `copy failed: ${copied.reason}`)
              }}
            />
          </Box>
        ))}
        {list.length > room && <Text dimColor>… {list.length - room} more</Text>}
      </Box>
    )
  })
}
